language: android
dist: trusty
android:
  components:
  - tools
  - platform-tools
  - tools
  - build-tools-29.0.3
  - android-R
  - extra
script:
  - "./gradlew :app:assembleRelease"
before_install:
  - android-update-sdk --list
  - openssl aes-256-cbc -K $encrypted_61eba3fac051_key -iv $encrypted_61eba3fac051_iv
    -in Gadgetry.jks.enc -out Gadgetry.jks -d
  - chmod +x gradlew
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
notifications:
  email:
  - 2331490629@qq.com
deploy:
  provider: releases
  api_key:
    secure: k9tbRCiqFedG4mXmTMQIZkNBvO1qnZeXaPpClMrRUXNUtZwAL2EMFSwDHjCYagybAGaSY+031nr9FM+399A7UpB8F/lGJy/SVlhrtLjS+rzAtpPN3A1xF/2U7lN3EopAvQu/tU6sBfvDSr/VlJWlhFmcx9h8fUZINdRGNgUxqxV2IVh9DzQNOE2VvHZ+V3+KWGKo8NGdTHEPFN8HTVO2Kj1Zgqasi+VGtB2rh38Ae91qvoIIpzS8uaOpiewL5gmv2QoGBdA67vJJ9FWc+or3Qtr2kaTtziLKKiwK0pnqKZjmrzur8eGr58Z2140i3CHDcLLISz/yDDSgjIhoLQ7F0oRKy81V9jfWSnfYKmhGEXWVID1pYo2thZz4yupYXWyd/hcd1Lerof3oy5sITZMd2NGx2K+qu2gHiLZR2xKRxFeeBDdhk7Bb0yOU1QqDpjLwIpMaoQCv7gM8aQbx/R6HfadmQlyuQpB2x5HRXz31yBoayNMrsGRVZcrWXQV/snDxHDezoWPDrYhRn23rNgib5mGsvpcBBEkvsYl4peUyS51+ufcCQxT0k+2biVkD/u6RucW3EcIwxAeatY5c2zP59CFstvKQ4/qrl8k1PX0IYm6UbDJxQ92rqddx5dXDUhegDc1h/kE5xL1q0Fa+wwHxrWjLMPcxy+SA7RWgcHkcOKo=
  skip_cleanup: true
  file: app/build/outputs/apk/release/app-release.apk
  on:
    repo: gggxbbb/tujian_kotlin
